<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Router.Infrastructure</RootNamespace>
    <AssemblyName>Router.Infrastructure</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Router.Contracts\Router.Contracts.csproj" />
    <PackageReference Include="SqlSugarCore" Version="5.1.4.221" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.12" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.12" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.12" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.12" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="10.0.12" />
    <PackageReference Include="CSRedisCore" Version="3.8.807" />
    <PackageReference Include="Polly" Version="8.8.0" />
  </ItemGroup>
</Project>
