<script setup lang="ts">
import { computed, h, reactive, ref, watch } from 'vue'
import { useQuery, useQueryClient } from '@tanstack/vue-query'
import { useDialog, useMessage, NAlert, NButton, NCard, NDataTable, NEmpty, NForm, NFormItem, NIcon, NInput, NInputNumber, NModal, NPagination, NSelect, NSpin, NSpace, NTag } from 'naive-ui'
import type { DataTableColumns } from 'naive-ui'
import { api, type ProxyEndpoint, type ProxySubscription } from '@/services/api'
import { RefreshOutline } from '@vicons/ionicons5'
import ResponsiveFilterPanel from '@/components/ResponsiveFilterPanel.vue'

const message = useMessage(); const dialog = useDialog(); const queryClient = useQueryClient(); const page = ref(1); const pageSize = ref<20 | 50 | 100>(20); const selectedSubscriptionIds = ref<string[]>([]); const state = ref('')
const subscriptionsQuery = useQuery({ queryKey: ['proxy-subscriptions'], queryFn: api.subscriptions })
const query = useQuery({ queryKey: computed(() => ['proxies', page.value, pageSize.value, selectedSubscriptionIds.value, state.value]), queryFn: () => api.proxies({ page: page.value, pageSize: pageSize.value, subscriptionIds: selectedSubscriptionIds.value, state: state.value }) })
watch([selectedSubscriptionIds, state], () => { page.value = 1 })
const subscriptionRows = computed(() => subscriptionsQuery.data.value ?? []); const proxyRows = computed(() => query.data.value?.items ?? [])
const subscriptionOptions = computed(() => subscriptionRows.value.map(item => ({ label: `${item.name} · ${item.endpointCount} 节点`, value: item.id })))
const stateOptions = [{ label: '全部节点状态', value: '' }, { label: 'Active', value: 'Active' }, { label: 'Draining', value: 'Draining' }, { label: 'Disabled', value: 'Disabled' }]
const schemeOptions = [{ label: 'HTTP', value: 'http' }, { label: 'HTTPS', value: 'https' }, { label: 'SOCKS5', value: 'socks5' }]
const form = reactive({ host: '', port: 8080, scheme: 'http', username: '', password: '' }); const subscriptionForm = reactive({ name: '', url: '', scheme: 'http', refreshInterval: '1H' }); const editingSubscriptionId = ref<string | null>(null); const showModal = ref(false); const showSubscriptionModal = ref(false); const saving = ref(false); const subscriptionSaving = ref(false); const probingId = ref<string | null>(null)
const subscriptionColumns: DataTableColumns<ProxySubscription> = [
  { title: '来源', key: 'name' }, { title: '节点', key: 'endpointCount' }, { title: '刷新周期', key: 'refreshIntervalMinutes', render: row => formatRefreshInterval(row.refreshIntervalMinutes) },
  { title: '状态', key: 'status', render: row => h(NTag, { type: row.lastError ? 'error' : 'success', round: true }, { default: () => row.lastError ? '失败' : '正常' }) },
  { title: '操作', key: 'actions', width: 230, render: row => h('div', { class: 'table-actions' }, [h(NButton, { size: 'small', tertiary: true, onClick: () => openSubscriptionEdit(row) }, { default: () => '编辑' }), h(NButton, { size: 'small', tertiary: true, circle: true, 'aria-label': `刷新订阅 ${row.name}`, title: '刷新订阅', onClick: () => refreshSubscription(row) }, { default: () => h(NIcon, { component: RefreshOutline }) }), h(NButton, { size: 'small', tertiary: true, type: 'error', onClick: () => confirmDeleteSubscription(row) }, { default: () => '删除' })]) },
]
const columns: DataTableColumns<ProxyEndpoint> = [
  { title: '节点', key: 'address', render: row => `${row.host}:${row.port}` }, { title: '协议', key: 'scheme', render: row => row.scheme.toUpperCase() }, { title: '延迟', key: 'latencyMs', render: row => row.latencyMs ? `${row.latencyMs} ms` : '—' }, { title: '速度', key: 'speed', render: row => row.averageSpeedBytesPerSecond ? `${(row.averageSpeedBytesPerSecond / 1024).toFixed(1)} KB/s` : '—' }, { title: '探测', key: 'probeStatus', render: row => h('div', { class: 'proxy-probe-cell' }, [h(NTag, { type: row.probeStatus === 'Healthy' ? 'success' : row.probeStatus === 'Failed' ? 'error' : 'default', round: true }, { default: () => row.probeStatus }), row.probeError ? h('small', { class: 'proxy-probe-error' }, row.probeError) : null]) }, { title: '状态', key: 'state', render: row => h(NTag, { type: row.state === 'Active' ? 'success' : 'warning', round: true }, { default: () => row.state }) },
  { title: '操作', key: 'actions', width: 170, render: row => h('div', { class: 'table-actions' }, [h(NButton, { size: 'small', tertiary: true, loading: probingId.value === row.id, onClick: () => probe(row) }, { default: () => '测速' }), h(NButton, { size: 'small', tertiary: true, type: 'error', onClick: () => confirmDelete(row) }, { default: () => '删除' })]) },
]
function openCreate() { Object.assign(form, { host: '', port: 8080, scheme: 'http', username: '', password: '' }); showModal.value = true }
function openSubscriptionCreate() { editingSubscriptionId.value = null; Object.assign(subscriptionForm, { name: '', url: '', scheme: 'http', refreshInterval: '1H' }); showSubscriptionModal.value = true }
function openSubscriptionEdit(row: ProxySubscription) { editingSubscriptionId.value = row.id; Object.assign(subscriptionForm, { name: row.name, url: row.url, scheme: row.scheme.toLowerCase(), refreshInterval: formatRefreshInterval(row.refreshIntervalMinutes) }); showSubscriptionModal.value = true }
async function saveSubscription() { if (!subscriptionForm.name.trim() || !/^https?:\/\//i.test(subscriptionForm.url.trim()) || !/^[1-9]\d*[HM]$/i.test(subscriptionForm.refreshInterval.trim())) { message.warning('请填写有效的名称、http(s) 地址和刷新周期'); return }; subscriptionSaving.value = true; try { await api.saveSubscription({ ...subscriptionForm, id: editingSubscriptionId.value ?? undefined, name: subscriptionForm.name.trim(), url: subscriptionForm.url.trim(), refreshInterval: subscriptionForm.refreshInterval.trim().toUpperCase() }); showSubscriptionModal.value = false; message.success(editingSubscriptionId.value ? '订阅已更新' : '订阅已保存，后台正在拉取节点'); editingSubscriptionId.value = null; void queryClient.invalidateQueries({ queryKey: ['proxy-subscriptions'] }); void queryClient.invalidateQueries({ queryKey: ['proxies'] }) } catch (error) { message.error(error instanceof Error ? error.message : '保存失败') } finally { subscriptionSaving.value = false } }
async function save() { if (!form.host.trim() || form.port < 1 || form.port > 65535) { message.warning('请输入正确的代理地址和端口'); return }; saving.value = true; try { await api.saveProxy({ ...form, host: form.host.trim() }); await queryClient.invalidateQueries({ queryKey: ['proxies'] }); showModal.value = false; message.success('代理已保存') } catch (error) { message.error(error instanceof Error ? error.message : '保存失败') } finally { saving.value = false } }
async function refreshSubscription(row: ProxySubscription) { try { await api.refreshSubscription(row.id); await queryClient.invalidateQueries({ queryKey: ['proxy-subscriptions'] }); await queryClient.invalidateQueries({ queryKey: ['proxies'] }); message.success('订阅刷新已加入后台队列，节点测速会在后台完成') } catch (error) { message.error(error instanceof Error ? error.message : '刷新失败') } }
function confirmDeleteSubscription(row: ProxySubscription) { dialog.warning({ title: '删除订阅', content: `确定删除“${row.name}”及其节点吗？`, positiveText: '删除', negativeText: '取消', onPositiveClick: async () => { await api.deleteSubscription(row.id); await queryClient.invalidateQueries({ queryKey: ['proxy-subscriptions'] }); await queryClient.invalidateQueries({ queryKey: ['proxies'] }); message.success('订阅已删除') } }) }
function confirmDelete(row: ProxyEndpoint) { dialog.warning({ title: '删除代理', content: `确定删除 ${row.host}:${row.port} 吗？`, positiveText: '删除', negativeText: '取消', onPositiveClick: async () => { await api.deleteProxy(row.id); await queryClient.invalidateQueries({ queryKey: ['proxies'] }); message.success('节点已删除') } }) }
async function probe(row: ProxyEndpoint) { probingId.value = row.id; try { const result = await api.probeProxy(row.id); await queryClient.invalidateQueries({ queryKey: ['proxies'] }); if (result.success) message.success(`测速完成：${result.latencyMs} ms`); else message.warning(`测速失败：${result.error || result.status}`) } catch (error) { message.error(error instanceof Error ? error.message : '探测失败') } finally { probingId.value = null } }
function formatRefreshInterval(minutes: number) { return minutes % 60 === 0 ? `${minutes / 60}H` : `${minutes}M` }
</script>

<template>
  <NCard title="订阅来源" :bordered="false" class="table-card"><template #header-extra><NSpace><NButton secondary @click="openSubscriptionCreate">添加订阅</NButton><NButton type="primary" @click="openCreate">添加代理</NButton></NSpace></template><NSpin v-if="subscriptionsQuery.isPending.value" /><NAlert v-else-if="subscriptionsQuery.isError.value" type="error" title="订阅加载失败">请刷新后重试。</NAlert><NDataTable v-else :columns="subscriptionColumns" :data="subscriptionRows" :bordered="false"><template #empty><NEmpty description="还没有代理订阅" /></template></NDataTable></NCard>
  <NCard :bordered="false" class="table-card"><ResponsiveFilterPanel variant="plain" title="筛选代理"><div class="filter-row"><NSelect v-model:value="selectedSubscriptionIds" multiple clearable :options="subscriptionOptions" placeholder="选择订阅来源（可多选）" /><NSelect v-model:value="state" :options="stateOptions" /></div></ResponsiveFilterPanel><NSpin v-if="query.isPending.value" /><NAlert v-else-if="query.isError.value" type="error" title="代理加载失败">请刷新后重试。</NAlert><NDataTable v-else :columns="columns" :data="proxyRows" :scroll-x="980" :bordered="false"><template #empty><NEmpty description="还没有代理节点" /></template></NDataTable><div class="table-footer"><span>共 {{ query.data.value?.total ?? 0 }} 个节点</span><div class="table-pagination"><NButton secondary circle :loading="query.isFetching.value" aria-label="刷新代理列表" title="刷新" @click="query.refetch()"><template #icon><NIcon :component="RefreshOutline" /></template></NButton><NPagination v-model:page="page" v-model:page-size="pageSize" :page-count="query.data.value?.totalPages ?? 1" :page-sizes="[20, 50, 100]" show-size-picker /></div></div></NCard>
  <NModal v-model:show="showModal" preset="card" title="添加代理" style="width: min(520px, calc(100vw - 32px))"><NForm label-placement="top"><NFormItem label="协议"><NSelect v-model:value="form.scheme" :options="schemeOptions" /></NFormItem><div class="form-row"><NFormItem label="主机" class="grow"><NInput v-model:value="form.host" /></NFormItem><NFormItem label="端口"><NInputNumber v-model:value="form.port" :min="1" :max="65535" /></NFormItem></div><div class="form-row"><NFormItem label="用户名" class="grow"><NInput v-model:value="form.username" /></NFormItem><NFormItem label="密码" class="grow"><NInput v-model:value="form.password" type="password" show-password-on="click" /></NFormItem></div><div class="modal-actions"><NButton @click="showModal = false">取消</NButton><NButton type="primary" :loading="saving" @click="save">保存代理</NButton></div></NForm></NModal>
  <NModal v-model:show="showSubscriptionModal" preset="card" :title="editingSubscriptionId ? '编辑代理订阅' : '添加代理订阅'" style="width: min(520px, calc(100vw - 32px))"><NForm label-placement="top"><NFormItem label="名称"><NInput v-model:value="subscriptionForm.name" /></NFormItem><NFormItem label="地址"><NInput v-model:value="subscriptionForm.url" placeholder="https://example.com/proxies.txt" /></NFormItem><NFormItem label="节点协议"><NSelect v-model:value="subscriptionForm.scheme" :options="schemeOptions" /></NFormItem><NFormItem label="刷新周期"><NInput v-model:value="subscriptionForm.refreshInterval" placeholder="2H / 30M" /></NFormItem><div class="modal-actions"><NButton @click="showSubscriptionModal = false">取消</NButton><NButton type="primary" :loading="subscriptionSaving" @click="saveSubscription">{{ editingSubscriptionId ? '保存修改' : '保存订阅' }}</NButton></div></NForm></NModal>
</template>
